# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isImportant', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineJudgeApp.Blog')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compiler',
            fields=[
                ('compiler_id', models.AutoField(primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contest_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetaken', models.IntegerField()),
                ('rating_change', models.IntegerField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineJudgeApp.Contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('prob_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('time_limit', models.IntegerField()),
                ('mem_limit', models.IntegerField()),
                ('addedToPractice', models.BooleanField(default=False)),
                ('user_solved', models.IntegerField(default=0)),
                ('checker', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ProbTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1500)),
                ('photo', models.ImageField(upload_to='users')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.CharField(max_length=3)),
                ('compiler_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OnlineJudgeApp.Compiler')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProbContest',
            fields=[
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='OnlineJudgeApp.Problem')),
                ('index', models.IntegerField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineJudgeApp.Contest')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineJudgeApp.Problem'),
        ),
        migrations.AddField(
            model_name='submission',
            name='prob_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineJudgeApp.Problem'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='probtag',
            name='prob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineJudgeApp.Problem'),
        ),
        migrations.AddField(
            model_name='probtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineJudgeApp.Tag'),
        ),
        migrations.AddField(
            model_name='problem',
            name='setter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='probtag',
            unique_together=set([('prob', 'tag')]),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set([('contest', 'user')]),
        ),
    ]
