# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-28 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJudgeApp', '0004_auto_20171027_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='checker',
            field=models.TextField(),
        ),
    ]
