# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-28 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJudgeApp', '0005_auto_20171028_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='probcontest',
            old_name='index',
            new_name='idx',
        ),
    ]
