# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-28 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJudgeApp', '0006_auto_20171028_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='setter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
