# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-28 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJudgeApp', '0007_auto_20171028_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probcontest',
            name='idx',
            field=models.CharField(max_length=1),
        ),
    ]
