# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-02 23:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OnlineJudgeApp', '0008_auto_20171028_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='regnConfirm',
            fields=[
                ('regn_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
