# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-02 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJudgeApp', '0009_regnconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='regnconfirm',
            name='hashval',
            field=models.TextField(default='qwerty'),
            preserve_default=False,
        ),
    ]
