# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-06 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJudgeApp', '0011_remove_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='compiler_id',
        ),
        migrations.DeleteModel(
            name='Compiler',
        ),
    ]
