# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-16 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJudgeApp', '0015_auto_20171113_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isRated',
            field=models.BooleanField(default=False),
        ),
    ]
